// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsYP_oUMfUaKBvmZJyCkLVw19hxWTZmjo',
    appId: '1:382615137326:web:34190ed81806126e4083bf',
    messagingSenderId: '382615137326',
    projectId: 'interviewai-4b88d',
    authDomain: 'interviewai-4b88d.firebaseapp.com',
    storageBucket: 'interviewai-4b88d.firebasestorage.app',
    measurementId: 'G-W9CLCLYS9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGz3Kf5yMJOabhpb53wzlrh_0rxTBUWxE',
    appId: '1:382615137326:android:bf14468ce494c8b54083bf',
    messagingSenderId: '382615137326',
    projectId: 'interviewai-4b88d',
    storageBucket: 'interviewai-4b88d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTiVQXXa_5swde2KXDz-5OhHgw4C34L98',
    appId: '1:382615137326:ios:2cb9e09142e8ad764083bf',
    messagingSenderId: '382615137326',
    projectId: 'interviewai-4b88d',
    storageBucket: 'interviewai-4b88d.firebasestorage.app',
    iosClientId: '382615137326-rq62gfev3fj0jl91vgs43a453nc9dj79.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTiVQXXa_5swde2KXDz-5OhHgw4C34L98',
    appId: '1:382615137326:ios:2cb9e09142e8ad764083bf',
    messagingSenderId: '382615137326',
    projectId: 'interviewai-4b88d',
    storageBucket: 'interviewai-4b88d.firebasestorage.app',
    iosClientId: '382615137326-rq62gfev3fj0jl91vgs43a453nc9dj79.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsYP_oUMfUaKBvmZJyCkLVw19hxWTZmjo',
    appId: '1:382615137326:web:8158933ebb87d88c4083bf',
    messagingSenderId: '382615137326',
    projectId: 'interviewai-4b88d',
    authDomain: 'interviewai-4b88d.firebaseapp.com',
    storageBucket: 'interviewai-4b88d.firebasestorage.app',
    measurementId: 'G-BG10DCBCKD',
  );
}
